Test QElo filter technology endpoint /survey/admin/QElo_filter_technology
qxf2/qxf2-survey pull request #56
Opened 2022-12-27 09:23 UTC by shivahari

1. Updated the `requirements.txt` file in the `backend` dir to include the modules required for tests
2. Added a `conftest.py` file to mark the `backend` dir as `pytest` root
3. Created a `tests` directory inside `backend` to track the backend tests
4. Added a test with parameters to validate the following scenarios:
    - Date range one year prior the the dates where data exists
    - Date range that covers all three weeks of existing data
    - Date range that covers only first  week of existing data
    - Date range that covers only first two weeks of existing data

2023-01-02 15:26 UTC, akkuldn requested changes
Can we have the tests folder in the root directory itself? Also the requirements needed for the test could be added as a new `requirements.txt` file inside the `tests` folder itself.

2023-01-03 07:19 UTC, shivahari commented
@akkuldn  The `tests` dir was added to `backend` to reduce file duplication.
Adding a  `tests` dir to `backend` prevents duplicating the `.env`& `requirements.txt` file. 
Also for a project with `React` frontend and a `Python` backend will it make more sense to have the respective `tests` in the `frontend` & `backend` directories?

2023-01-03 10:26 UTC, akkuldn commented
> @akkuldn The `tests` dir was added to `backend` to reduce file duplication. Adding a `tests` dir to `backend` prevents duplicating the `.env`& `requirements.txt` file. Also for a project with `React` frontend and a `Python` backend will it make more sense to have the respective `tests` in the `frontend` & `backend` directories?

Hey Shiva, what you said makes sense, I and Arun thought to have a common tests folder in the root directory as it would apply to both frontend and backend as well. But would having a conftest.py file in the backend be right? What do you think about having seperate subdirectories `frontend-tests` and `backend-tests` within the tests folder under the root directory. The conftest can be added inside the tests folder.
Directory structure would look something like this:
```
- Root_directory/
     - frontend/
     -backend/
     - tests/
           - frontend_tests/
           - backend_tests/
           - conftest.py
           - requirements.txt
           - .env
```

2023-01-03 10:48 UTC, shivahari commented
> > @akkuldn The `tests` dir was added to `backend` to reduce file duplication. Adding a `tests` dir to `backend` prevents duplicating the `.env`& `requirements.txt` file. Also for a project with `React` frontend and a `Python` backend will it make more sense to have the respective `tests` in the `frontend` & `backend` directories?
> 
> Hey Shiva, what you said makes sense, I and Arun thought to have a common tests folder in the root directory as it would apply to both frontend and backend as well. But would having a conftest.py file in the backend be right? What do you think about having seperate subdirectories `frontend-tests` and `backend-tests` within the tests folder under the root directory. The conftest can be added inside the tests folder. Directory structure would look something like this:
> 
> ```
> - Root_directory/
>      - frontend/
>      - backend/
>      - tests/
>            - frontend_tests/
>            - backend_tests/
>            - conftest.py
>            - requirements.txt
>            - .env
> ```

Are we going to use `pytest` for frontend tests too?, I was thinking we will be using a `JS` framework to test the `React` frontend.

The `conftest.py` file, if added, needs to be in the `backend` directory. It marks the project root & allows the `.env` file in `backend` directory to be used for the tests too.

Adding `frontend_tests` & `backend_tests` would warrant us to add a `pytest.ini` file to run a recursive search to collect the tests on the `tests` directory, I am not sure how the latest version of `pytest` collects the tests though.

This is my suggestion for directory structure:

```
|-- LICENSE
|-- README.md
|-- __pycache__
|-- awareness_score
|-- backend
        |-- __pycache__
        |-- app
        |-- conftest.py
        |-- db_backup_and_restore
        |-- requirements.txt
        |-- tests
            |-- __pycache__
            |-- test_technology_between_dates.py
|-- frontend
|-- migration_test.py
```

2023-01-03 11:22 UTC, akkuldn commented
> > > @akkuldn The `tests` dir was added to `backend` to reduce file duplication. Adding a `tests` dir to `backend` prevents duplicating the `.env`& `requirements.txt` file. Also for a project with `React` frontend and a `Python` backend will it make more sense to have the respective `tests` in the `frontend` & `backend` directories?
> > 
> > 
> > Hey Shiva, what you said makes sense, I and Arun thought to have a common tests folder in the root directory as it would apply to both frontend and backend as well. But would having a conftest.py file in the backend be right? What do you think about having seperate subdirectories `frontend-tests` and `backend-tests` within the tests folder under the root directory. The conftest can be added inside the tests folder. Directory structure would look something like this:
> > ```
> > - Root_directory/
> >      - frontend/
> >      - backend/
> >      - tests/
> >            - frontend_tests/
> >            - backend_tests/
> >            - conftest.py
> >            - requirements.txt
> >            - .env
> > ```
> 
> Are we going to use `pytest` for frontend tests too?, I was thinking we will be using a `JS` framework to test the `React` frontend.
> 
> The `conftest.py` file, if added, needs to be in the `backend` directory. It marks the project root & allows the `.env` file in `backend` directory to be used for the tests too.
> 
> Adding `frontend_tests` & `backend_tests` would warrant us to add a `pytest.ini` file to run a recursive search to collect the tests on the `tests` directory, I am not sure how the latest version of `pytest` collects the tests though.
> 
> This is my suggestion for directory structure:
> 
> ```
> |-- LICENSE
> |-- README.md
> |-- __pycache__
> |-- awareness_score
> |-- backend
>         |-- __pycache__
>         |-- app
>         |-- conftest.py
>         |-- db_backup_and_restore
>         |-- requirements.txt
>         |-- tests
>             |-- __pycache__
>             |-- test_technology_between_dates.py
> |-- frontend
> |-- migration_test.py
> ```

Yes Shiva, I agree with you. I think we can go with your design. Could you please update the `.env.example` file with the URL variable used in the test. 
Along with that  can you also please add the following data as well in the `.env.example` file
```
#Graphql credentials
GRAPHQl_USERNAME = ""
GRAPHQL_PASSWORD = ""
```

2023-01-04 04:52 UTC, shivahari commented
@akkuldn I have added the `GraphQL credentials` & `URL` default params to the `.env.example` file.

2023-01-04 11:15 UTC, merged