Added test to verify not responded users endpoint
qxf2/qxf2-survey pull request #57
Opened 2022-12-27 10:17 UTC by sravantit25

Tests for survey API endpoint '/survey​/admin​/not_responded_users' that fetches all the users that have not responded to the survey.

Test cases:
 * Check the employees that have not responded to the survey and are active
 * Mock response given from an employee and verify that the employee is not listed 
 
For the second test case, I have mocked response for an employee by establishing a relationship. Have done this for 'GIVEN'. 

Before running this script, run the neo4j_restore script.

2023-01-03 06:47 UTC, akkuldn requested changes
Hi Sravanti, can we just have the test to get all the active users from `not_responded_users` endpoint for now? Because any change to the the synthetic data in DB would make it difficult for tests to run in parallel.  The current test  wouldn't fit the first round of tests based on synthetic data. Edits to data should be run only after the read/fetch tests based on synthetic data are run

2023-01-04 15:52 UTC, sravantit25 commented
> Hi Sravanti, can we just have the test to get all the active users from `not_responded_users` endpoint for now? Because any change to the the synthetic data in DB would make it difficult for tests to run in parallel. The current test wouldn't fit the first round of tests based on synthetic data. Edits to data should be run only after the read/fetch tests based on synthetic data are run

I think if we do that, we will not be testing all scenarios. Yes, the test would return all active users if I just keep the existing data and call the endpoint because no one responded yet. I think we should also test the case where a user actually responded and we do not return that user.

Ideally tests should be independent from each other and should not interfere other tests. We could solve this by mocking GraphQL responses and not actually use the GraphQL endpoint. Since this is a unit test, doing that would make all tests independent. If not, we can run these tests in sequence, that way we know what would be the state of the DB at the beginning of each test and write the test in that way.

Another way is to have a "before" script and "after" script for each test, which actually brings the DB to required state when "before" runs and clear/reset the state when the "after" script runs.

That said, I have removed the test data (commented out) that changes the synthetic data. I let the method be so that later when we make the tests independent we can use that.

2023-01-05 08:37 UTC, akkuldn commented
Hi @sravantit25 , I agree, but if we mock the API endpoints then that would beat the purpose of having synthetic data itself in the first place right?  I have written new tests recently , in which testing one API depends on the output from other API, but that could be run separately. Arun & I thought of having the first set of tests to be run independently and in parallel.
Could you please remove the commented out code and raise a separate PR for that, we could use that separately. 
In the current code can you please change the import of variables `URL` and `API_KEY` to have it imported from an .env file within the tests folder. You can do this with decouple library. Since we are changing the location of tests directory from `root` to `backend` folder, this would make it easier for me to relocate you're test

2023-01-18 16:09 UTC, sravantit25 commented
> Hi Sravanti, can we just have the test to get all the active users from `not_responded_users` endpoint for now? Because any change to the the synthetic data in DB would make it difficult for tests to run in parallel. The current test wouldn't fit the first round of tests based on synthetic data. Edits to data should be run only after the read/fetch tests based on synthetic data are run

@akkuldn I have made the changes and pushed the changes. So sorry for such delay.

2023-01-23 14:08 UTC, akkuldn approved these changes

2023-01-23 14:09 UTC, merged