Test to validate employee details by email
qxf2/qxf2-survey pull request #58
Opened 2022-12-27 10:21 UTC by indiranell

Added test for survey API to validate employee details by email

Covered below scenarios:

- Run the endpoint by passing an email that exists in the database and validate the response data
- Run the endpoint by passing an email that does not exist in database and validate the response

2023-01-03 07:08 UTC, akkuldn requested changes

2023-01-03 10:16 UTC, indiranell commented on tests/test_responses_employee_by_email.py
> +    assert response_data == expected_response
@akkuldn 
`response_data == expected_response` would compare equal if and only if they have the same (key, value) pairs regardless of ordering.  So, even if the `lastname` comes before `firstname` the test will not fail until the value is different.

2023-01-04 11:27 UTC, akkuldn commented on tests/test_responses_employee_by_email.py
> +    assert response_data == expected_response
Ah I see, Thanks for clarifying @indiranell

2023-01-04 11:42 UTC, akkuldn approved these changes

2023-01-04 11:43 UTC, merged